config/routes.rb
Rails.application.routes.draw do
  get 'citations/index'

  root 'citations#index'
  resources :citations
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/citation.rb
class Citation < ApplicationRecord
  validates :title, length: { maximum: 500 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/citations_controller.rb
class CitationsController < ApplicationController
  def index
    @citations = Citation.all.paginate(:page => params[:page], :per_page => 12)
  end

  def new
    @citation = Citation.new
  end

  def create
    @citation = Citation.new(citation_params)

    if @citation.save
      redirect_to citations_path
    else
      render 'new'
    end
  end

  private

  def citation_params
    params.require(:citation).permit(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/citations_helper.rb
module CitationsHelper
end

app/views/citations/index.html.erb
<h1>Listing citations</h1>
<div class='button'>
 <%= link_to '<button type="button">New Citation</button>'.html_safe, new_citation_path %>
</div>

<table id="citations">
  <tr>
    <th>Quotes</th>
    <th>Date</th>
  </tr>
 
  <% @citations.each do |citation| %>
    <tr>
      <td><%= citation.title %></td>
      <td><%= citation.created_at.strftime("%d %B %Y") %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @citations %>

app/views/citations/new.html.erb
<div class='form'>
  <%= simple_form_for @citation do |f| %>
    <%= f.input :title %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Netguru</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>